steps:
  - label: "Test"
    command:
      - "bin/test"
    plugins:
      - docker#v3.2.0:
          image: "722349771793.dkr.ecr.ap-southeast-2.amazonaws.com/rust-ci:latest"
          mount-ssh-agent: true
          environment:
            - "AWS_DEFAULT_REGION"
            - "CI"
            - "BUILDKITE_COMMIT"
            - "BUILDKITE_BRANCH"
